Repository OPUS4/application, pull requests merged in 2025-03, with the labels that each got.

#1286 #1285 Fix bug checking for contactable authors
  modules/frontdoor/models/Authors.php
  tests/modules/frontdoor/models/AuthorsTest.php
Labels: bug

#1287 #1283: Limiting number of imported authors to avoid crash
  public/layouts/opus4/js/doiAssist.js
  public/layouts/opus4/js/getDoi.js
Labels: bug, enhancement

#1292 Adding "aria-label" to search input element
  modules/solrsearch/views/scripts/index/simpleSearchForm.phtml
  tests/support/ControllerTestCase.php
Labels: enhancement
